### ISSUE TITLE
Regular adb terminal

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#367]
Add support to use the regular terminal and not adb shell.

**Comment by yume-chan** [comment]
What's the difference between regular terminal and adb shell? How to start a regular terminal?

**Comment by upintheairsheep** [comment]
Adb without the shell. Just adb. Not adb shell.

**Comment by yume-chan** [comment]
It won't support native ADB command line arguments because:

1. It's a library, providing programmatic API for ADB. It's intended to be integrated into other projects, not used solely.
2. It now mainly targets browser environment (although it can also run on Node.js, if a compatible backend was provided), which doesn't have a command line interface.
3. It's architecture is too different from native ADB, it's impossible to implement some features in a cross-platform way. For example, its reverse tunnel accepts a callback, instead of listening a TCP port (because there is no TCP server support in browsers)
