### ISSUE TITLE
Non standard Node.js modules

### ISSUE THREAD

**Issue by ramiresviana** [yume-chan/ya-webadb#387]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.10

### Runtime

Linux

### Device

Not applicable

### Describe the bug

Is not possible to use the `@yume-chan/adb` on a bare npm package, trying to import it gives errors like `MODULE_NOT_FOUND` and `ERR_MODULE_NOT_FOUND`.

```js
// index.js
import { Adb } from "@yume-chan/adb"
```

Gives the following error:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/ya-webadb/index.js' imported from /path/to/ya-webadb/`

To make it work, i have to use a experimental option `--es-module-specifier-resolution=node` and also change the `module` field to `main` on every package.json of the libraries.

### Steps to reproduce

1. run `npm init`.
2. run `npm install @yume-chan/adb`.
3. create `index.js` with import syntax.
4. run `nodejs index.js`.

**Comment by yume-chan** [comment]
Thanks for trying it in Node.js.

As for the "non-standard" ES Module format, AFAIK the standard AND the whole ecosystem is a hot mess now. I used to ship both CJS and ESM, at some point I wanted to use `import.meta.url` to import assets in Webpack, so CJS support is removed, leaving this half-way done ESM format.

I can change `module` to `main`, Webpack [already supports that](https://webpack.js.org/configuration/resolve/#resolvemainfields), but I can't add file extensions (and not use folder imports) because TypeScript withdrawn Node ESM support from 4.5 due to multiple unresolved questions (Microsoft/TypeScript#46452) so I have no tooling support.

Plus I'm working on a huge [rewrite](https://github.com/yume-chan/ya-webadb/compare/feat/web-streams) to use Web Streams API (and I have my full-time job) so TBH I can't find time to investigate how to properly support Node.js.

If you can help me, I would recommend you working on the `feat/web-streams` branch, and using this repository's monorepo setup (see [CONTRIBUTE.md](https://github.com/yume-chan/ya-webadb/blob/master/CONTRIBUTE.md) to quickly prototype. Code on this branch will work, only slower, so I'm still refactoring and optimizing it.

You can create a new package by initialing it normally, then adding it to `rush.json`. Run `rush update` to install dependencies, and `rush build:watch` to continue transpiling TypeScript source files.

**Comment by yume-chan** [comment]
I pushed d9212b4dac6aa53eec52721515030e8f8b7fff4c to improve compatibility with Node.js.

Again, I don't have a real Node.js project to test, it only passes TypeScript compilation in `Node12` module and resolution mode.

I haven't published them to NPM, because the Web Stream branch is still not stable and optimized enough, so I still recommend develop and test your application on a fork with monorepo.

I will leave this issue open to track the publish process.

**Comment by yume-chan** [comment]
Version 0.0.12 published, and verified with Node.js v16.13.1
