### ISSUE TITLE
unable to use scrcpy screen on older phone

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [yume-chan/ya-webadb#389]
### Issue Checklist

- [x] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

chromium (deb version). linux solydx (debian-based)

### Device

android 5.1

### Describe the bug

getting black output of scrcpy (no input neither output received)

### Steps to reproduce

1. connect phone to browser - works
2. click 'play' icon in list  - works
3. try to use screen below - doesnt work
![Przechwycenie obrazu ekranu_2022-03-20_19-55-30](https://user-images.githubusercontent.com/97974194/159177987-d933540f-cdb7-48b2-a98b-ca7023c9f459.png)
(yes i know i have trashy phone but it works on deb-installed scrcpy locally, not on web)

**Comment by hacknorris-aka-penguin** [comment]
also here log:
```
[client] Server version: 1.22
[client] Server arguments: log_level=debug max_size=1080 bit_rate=4000000 lock_video_orientation=-1 tunnel_forward=true encoder_name=OMX.qcom.video.encoder.avc send_device_meta=false send_dummy_byte=false codec_options=profile=1,level=2048


[server] DEBUG: Codec option set: level (Integer) = 2048
[server] DEBUG: Creating encoder by name: 'OMX.qcom.video.encoder.avc'
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0x80001001
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:580)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:274)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:73)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:100)
	at com.genymobile.scrcpy.Server.main(Server.java:326)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
```

**Comment by yume-chan** [comment]
What version of Chrome are you using? If you click the "Settings" button, is "WebCodecs" available in decoders list?

**Comment by hacknorris-aka-penguin** [comment]
moment. its chromium:
Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.11 (64-bit)
any codecs arent visible in settings (there isnt even decoders)

**Comment by hacknorris-aka-penguin** [comment]
and if you think i didnt googled error - i know that its caused by old scrcpy version ;p

**Comment by yume-chan** [comment]
> i know that its caused by old scrcpy version ;p

Actually, no :-)

The log already told you:

> [client] Server version: 1.22

(I'm working on a whole refactoring so not upgraded to 1.23 yet)

----

The true cause is your Chromium, and your device, are too old.

Before Chromium 95 and WebCodecs API, I use TinyH264 library to decode Scrcpy video stream. But because TinyH264 only supports Baseline profile and level 4.1, I requested the device to encode at this configuration.

While newer devices default to higher configurations, your device doesn't even support such a basic configuration.

If you have Chromium 95 or newer, then I use the WebCodecs API by default, which should supports any H.264 profile/level. So, I let the device choose which configuration it supports best and use that.

---

The native Scrcpy uses FFMpeg to decode video so it's basically same as the WebCodecs situation.

---

It's possible to add profile and level selection in settings, but I consider that to be too complex/rarely used. So, if you can, upgrade to a new Chromium version.

**Comment by hacknorris-aka-penguin** [comment]
its not in my distro sources ;p

**Comment by hacknorris-aka-penguin** [comment]
and there arent debs for degoogled chromium ;p (where me and recompiling by myself? )

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/161426787-3221559f-a92b-4753-9b85-7cd31522ff06.png)

You can use this new option.

**Comment by hacknorris-aka-penguin** [comment]
k. thk

**Comment by yume-chan** [comment]
CI build failed, please wait two more minutes.

**Comment by hacknorris-aka-penguin** [comment]
lol
