### ISSUE TITLE
File manager & interactive shell - Root with DirtyCow

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#392]
DirtyCow is the best exploit to temporarily root android devices with Marshmallow 6.0 to the earliest available builds of Android available. This means extra root access to access more files in the explorer or shell harder.

**Comment by yume-chan** [comment]
I can only find https://github.com/timwr/CVE-2016-5195 and its forks. According to https://github.com/timwr/CVE-2016-5195/issues/9, DirtyCow on Android won't give you true root access because SELinux still restrict the permissions.

Using DirtyCow itself it's possible to overwrite any existing file, but they will be reverted after reboot so still useless.

Anyway, File Manager and Interactive Shell will have root access if you root your device using normal methods.
