### ISSUE TITLE
Can not add reverse socket connection

### ISSUE THREAD

**Issue by stylesuxx** [yume-chan/ya-webadb#410]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.14

### Runtime

Linux, Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### Device

DJI FPV goggles V2

### Describe the bug

I am trying to add a reverse socket connection, basically what `adb reverse tcp:0 tcp:6666` does:
```javascript
const credentialStore = new AdbWebCredentialStore();
const device = await AdbWebUsbBackend.requestDevice();
const streams = await device.connect();
const adb = await Adb.authenticate(streams, credentialStore, undefined);
await adb.reverse.add("tcp:0", "tcp:6666", {
  onSocket: (packet, socket) => {
    //...
  }
});
```

Is resulting in this error:
```
Error: Stream ended
    at AdbBufferedStream.read (buffered.ts:49:1)
```

I could trace it till here, seems something fails during de-serialization: https://github.com/yume-chan/ya-webadb/blob/d0a8257a2dd7e315bc191565695c22330e588f7a/libraries/adb/src/commands/reverse.ts#L95

### Steps to reproduce

```javascript
const credentialStore = new AdbWebCredentialStore();
const device = await AdbWebUsbBackend.requestDevice();
const streams = await device.connect();
const adb = await Adb.authenticate(streams, credentialStore, undefined);
await adb.reverse.add("tcp:0", "tcp:6666", {
  onSocket: (packet, socket) => {
    //...
  }
});
```

**Comment by yume-chan** [comment]
The second parameter (`localPort`) should be a number, the library automatically prepends `tcp:` to it.

In this library, the reverse connection doesn't really connect to a listening socket, instead it calls the third parameter (`handler`) with the connection. So, the second parameter only needs to be unique, the value doesn't have meaning, it can even be a random string. Just happened I choose it to be numbers. 

Maybe I will change it to accept any string in future.

**Comment by stylesuxx** [comment]
I am sorry - totally missed the type in the signature. But I still get the same error even if I pass a number.

**Comment by stylesuxx** [comment]
Your patch is looking good - I applied it locally and the handler is now being triggered with a socket.

**Comment by yume-chan** [comment]
Version 0.0.15 released with compatibility fix for Android 7 (and older) and some API changes.

Here is an example, I only tested it on Android 9 because this device has netcat.

https://github.com/yume-chan/ya-webadb/blob/12f88c355c63a8fbfc677adef1c2a5c6675195cb/apps/demo/src/pages/reverse.tsx#L17-L31

The handler now needs to return `true` to accept the connection, otherwise the dispatcher will ask the next handler (if any) and ultimately reject it. No packet will arrive before return, and `.pipeTo(new WritableStream())` is the most common method to handle a stream in Web Streams API.

The second parameter is now a string and it can be any value without null characters.

**Comment by stylesuxx** [comment]
Awesome - this is working fine for me so far, I can now get data from the socket.

**Comment by yume-chan** [comment]
Glad to hear that.
