### ISSUE TITLE
Unable to claim interface on ChromeOS

### ISSUE THREAD

**Issue by WindowsRefundDay** [yume-chan/ya-webadb#461]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

ChromeOS 105.0.5195.134 (Official Build) (64-bit) 

### Device

Lenovo Chromebook 300e 2nd Gen and Galaxy S21 running Android 12 OneUI 4.1 Android Security Patch Level 10/1

### Describe the bug

![image](https://user-images.githubusercontent.com/88746308/199545452-9d30bbdc-e6b2-4cad-9184-4f6a60d2cbea.png)
```
Failed to execute `claim interface` on USBDevice`: Unable to claim interface.
```
This error appears only on my chromebook and im only using a regular USBC to USBC cable

### Steps to reproduce

1. Plug in
2. Click connect (it would be nice if I can unpair it)
3. Error message

**Comment by yume-chan** [comment]
I'm not familiar with Chrome OS, although I know it works for at least one user on Chrome OS, and Samsung devices shouldn't have anything special either.

Make sure you don't have other apps accessing your device (like native ADB or Android Studio,). Otherwise please check the log by:

1. Open chrome://device-log/
2. Open the demo website
3. Connect your device and press connect
4. Switch to chrome://device-log and press Refresh

**Comment by WindowsRefundDay** [comment]
Here's what I was able to gather:
![image](https://user-images.githubusercontent.com/88746308/202208817-44e6b001-2f18-474d-8d20-41a6fc8e8e71.png)
The chromebook detects the device (S21) and asked my phone if it can allow access to phone data which I touched "yes" to.
It still shows the error unable to claim interface so I messed with the developer settings to see if I can do it.
I started off by revoking past USB ADB Authorizations which didn't work
Then I enabled 3AGT commands which didn't work.
The following is a screenshot where I tried again but it doesn't seem to have any interaction with this device

**Comment by yume-chan** [comment]
> it would be nice if I can unpair it

There is no "unpair" because it never "pair" with your device in the first place. The "Add" button only request the permission to communicate with your device from the browser. You can revoke the permission by clicking the "lock" icon in address bar.

![image](https://user-images.githubusercontent.com/1330321/204124081-d6f2fb90-5a27-41fd-97cd-ee37440d0aa9.png)

> This error appears only on my chromebook

Do you mean it works with another computer/OS?

---

Can you do this:

1. Open `chrome://usb-internals"
2. Switch to "Devices" tab
3. Click the "Inspect" button for your Android device
4. Expand all levels and take a screenshot of the full page

Like this:

![image](https://user-images.githubusercontent.com/1330321/204124287-558d0a7d-39af-487e-9484-70e0823955e6.png)

**Comment by WindowsRefundDay** [comment]
Thank you so much for replying 

> * Some Android devices can only be connected when in "file Transfer/MTP" mode, not "charging only"

For me it says "Transferring files / Android Auto" which I assume is the same as you mentioned

> * Some online documentation shows that ChromeOS will enable its own ADB server when developer mode is on or Linux mode is installed, do you have those?

I don't have Developer Mode or Linux mode 

> There is no "unpair" because it never "pair" with your device in the first place. The "Add" button only request the permission to communicate with your device from the browser. You can revoke the permission by clicking the "lock" icon in address bar.

Thank you so much for clarifying this! I didn't know revoking permissions was that easy!

> Do you mean it works with another computer/OS?

Yeah, I tried it on my windows pc with chromium

Here are some screenshots
![image](https://user-images.githubusercontent.com/88746308/204159826-a1c2dd22-768f-4a30-821c-b4530a36fb25.png)
![image](https://user-images.githubusercontent.com/88746308/204159856-139e7e2a-c477-4d6c-ae57-b2604ebe17e2.png)
 
Also I forgot to mention, it used to work. I cant remember if a software update changed this.

**Comment by dandv** [comment]
I also get `Unable to claim interface` on Brave 1.48.171, with a Samsung GS7 connected in recovery mode (TWRP), with the partitions mounted. `adb shell ls /data/data` works fine.

Here's `usb-internals`:

![image](https://user-images.githubusercontent.com/33569/226493014-2dd17a0f-3885-40bb-a9d8-8e1e9a901175.png)

Turns out there was an adb process accessing the device (found it via `ps`). After killing it, I can browse the files! :tada: 

Would be good to mention in a `Troubleshooting` section in the README how to make sure that no other processes are accessing the device. Some might not be named `adb`.

**Comment by yume-chan** [comment]
> Would be good to mention in a Troubleshooting section in the README how to make sure that no other processes are accessing the device. Some might not be named adb.

It's on the home page

![image](https://user-images.githubusercontent.com/1330321/226515351-b735c0f7-4fa8-43a8-a9b8-aa4ae81ad769.png)

**Comment by WindowsRefundDay** [comment]
I no longer use ya-webadb because I sold my phone but i'm gonna leave this open because some other people have the same issue ig.

**Comment by yume-chan** [comment]
For others with the same issue, please open a new issue with the required information.

This one will be closed.
