### ISSUE TITLE
Demo themes

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#555]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

I would like the addition of themes such as 

- OneUI
- Windows
- MacOS

this would not change or add any adb features. just a visual feature. this would only change the overall look of the website and allow the user to change the look to user preference. If this is impossible to do due to the way that the website is created, then you can close this issue as not planned. if it is possible, tell me, and I will try to create non-functional concept examples. 
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by glitch128** [comment]
hey, is this possible?

**Comment by yume-chan** [comment]
Today not many websites support multiple themes, plus I'm pretty bad at UI design, so this won't happen.

If you know some UI framework (for React) supports native OS themes, I will try to use that instead.

**Comment by parkerlreed** [comment]
I think even just a dark/light toggle would go a long way. Currently using Kiwi browser on Android because I can toggle dark mode and it applies to the PWA as well. Would be nice to have that available regardless of the browser.

![Screenshot_20230516-123337_Kiwi Browser](https://github.com/yume-chan/ya-webadb/assets/841440/a5d95131-23de-46a4-8b0e-4b7f603a9cca)

**Comment by yume-chan** [comment]
My plan is to create a new Web App for ease of use, using a UI framework I previously created for another project, which will have dark mode support. However, that will probably take at least two months.

**Comment by glitch128** [comment]
what is the project so I can see what the new page might look like?
