### ISSUE TITLE
Reading / writing to an adb socket over AdbDaemonTransport using WebUsb 

### ISSUE THREAD

**Issue by Unbrick** [yume-chan/ya-webadb#611]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.21

### Environment

Chrome 118, Android 13

### Device

OnePlus 8 Pro

### Describe the bug

I am trying to send and receive data over an AdbSocket. My current setup looks like follows:

```
// Initialize ADB connection
const connection: ReadableWritablePair<
          AdbPacketData,
          Consumable<AdbPacketInit>
        > = await device.connect();
        const credentialStore: AdbWebCredentialStore =
          new AdbWebCredentialStore();

        const transport: AdbDaemonTransport =
          await AdbDaemonTransport.authenticate({
            serial: device.serial,
            connection,
            credentialStore: credentialStore,
          });

        const adb: Adb = new Adb(transport);

// Open socket to target address
    const adbSocket= await adb?.createSocket('tcp:27042');


// Send and receive data

    const encoder = new TextEncoder();
    const encodedArray = encoder.encode('Test');
    const writer = adbSocket!.writable.getWriter();
    await writer.write(new Consumable(encodedArray));
    writer.releaseLock();

    console.log('Wrote to socket');

    const reader = adbSocket!.readable.getReader();
    const buffer = await reader.read();
    console.log('Read: ' + buffer);
    reader.releaseLock();
    console.log('Read from socket');
```

The service running on the target port should echo back all input but the reader.read() is never resolved.

### Steps to reproduce

1. Create a simple Next.js application with the code above
2. Connect to the device and open a socket connection
3. Write to the socket and wait for a answer

**Comment by yume-chan** [comment]
In https://github.com/tango-adb/old-demo/blob/74e9154e5e474812b9e9424b89e5d962d0c9d174/packages/demo/src/pages/forward.tsx I added a similar setup to you.

This page can be viewed at https://tango-adb.github.io/old-demo/forward

I'm running `ncat -l 27042 -k -c "xargs -n1 echo"` in Termux as an echo server. 

When device is connected, the page shows:

```text
connected
received: Hello
```

So I can send and receive data through a TCP socket.

I sent `Hello\n` because apparently ncat processes in lines.

A suggestion is using `readable.pipeTo` instead of `readable.getReader`, or at least call `reader.read` in a loop. ADB is a multiplexing protocol, not reading one stream will block all other streams.

**Comment by Unbrick** [comment]
Thank you for your quick response, that resolved it!
