### ISSUE TITLE
[Suggestion] Make available on Firefox. Then it can use Wifi ADB

### ISSUE THREAD

**Issue by garywill** [yume-chan/ya-webadb#618]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

Hi @yume-chan , 

The old web demo support Wifi ADB with websockify. Please make it available on the new app.tangoapp.dev too.

And although Firefox doesn't support webUSB, Firefox users can use Wifi ADB. Please make it available for Firefox also.

Currently I can't find any entrance for Wifi ADB if I don't have USB connected

### How should the API change?

.

**Comment by yume-chan** [comment]
I'm working on a desktop client. Because I don't like the size and (poor IPC) performance of Electron, the current direction is running a server locally and still using Web browsers to display UI (similar to HTTP-Toolkit, it will support Firefox).

Please subscribe https://github.com/tango-adb/feedback/issues/4 for future updates.
