### ISSUE TITLE
unzip through subprocess

### ISSUE THREAD

**Issue by NONGFAH** [yume-chan/ya-webadb#648]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.24

### Environment

windows 11、chrome 120.0.6099.217

### Device

honor pad view7 pro/ android 12

### Describe the bug

I use `subprocess` to unzip a file larger than 2GB, but after two minutes, the decompression is not complete, and no new files are being extracted. catch and finally were not called.

### Steps to reproduce

this is my code

      // 解压文件
      .then(() => this.adb!.subprocess.spawn(`unzip -o -d ${dirPath}/unZip ${fileName}`))
      .then(info =>  info.exit.then())
      .then(code => console.log(`解压退出码${code}`))
      .then(() => console.log(`解压成功,总耗时${(Date.now() - start) / 1000}秒`))
      .catch(info => console.error(info))
      .finally(() => console.log(`完成`))

**Comment by yume-chan** [comment]
I guess `unzip` filled its stdout buffer and is waiting for you to read them.

https://docs.tangoapp.dev/api/subprocess/#:~:text=the%20process%20exits.-,READ%20ALL%20STREAMS!,-ADB%20is%20a

Try piping `info.stdout` to a `WritableStream` (due to a bug `info.stdout.cancel()` doesn't work), or adding `> /dev/null` to your command line.

**Comment by NONGFAH** [comment]
think you ，there is a bug in `unzip tool`。
